[package]
name = "bak"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "MIT"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny", priority = -1 }
expect_used = "deny"
panic = "deny"
unwrap_used = "deny"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
